["0.0.0"]
origin = "file://.."
["0.0.0".depends-on]
utilada_curl = "*"
utilada_unit = "*"
[general]
description = "Shiny new project"
maintainers = [
"your@email.here",
]
maintainers-logins = [
"github-username",
]

