["0.1.0"]
origin = "file://.."
["0.1.0".depends-on]
utilada_curl = "*"
[general]
description = "A simple console program to auto ping server(s)"
maintainers = [
"skelic3@gmail.com",
"momozor4@gmail.com",
]
maintainers-logins = [
"momozor",
]

